WIP feat: Adding create books controller and create books routes
GrupoBien/BooksBackendAPI pull request #23
Opened 2022-06-08 23:52 UTC by Wazowski19

2022-06-09 02:11 UTC, servo98 requested changes

2022-06-09 02:11 UTC, servo98 commented on api/models/bookModel.txt
> +autores: String,
borrar

2022-06-09 02:11 UTC, servo98 commented on api/routes/index.js
> +import { booksCreateRouter } from "./booksCreateRouter.js";
falta registrar esta nueva ruta en el archivo api.js

2022-06-09 02:30 UTC, Wazowski19 commented on api/routes/index.js
> +import { booksCreateRouter } from "./booksCreateRouter.js";
Listo calixto

2022-06-09 02:39 UTC, servo98 approved these changes

2022-06-09 23:51 UTC, servo98 requested changes

2022-06-09 23:51 UTC, servo98 commented on api/controllers/booksCreateController.js
> +import Books from '../models/book.js'
importar del index

2022-06-10 00:09 UTC, servo98 approved these changes

2022-06-10 00:09 UTC, merged